const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const source=fs.readFileSync('madaar_web/firebase-service.js','utf8').replaceAll('import(','loadSDK(');
function storage(){const map=new Map();return {getItem:key=>map.get(key)||null,setItem:(key,value)=>map.set(key,value),removeItem:key=>map.delete(key),map};}
function environment(key){const writes=[],sessionStorage=storage(),localStorage=storage(),data={},auth={currentUser:null,authStateReady:async()=>{}};let callback;
 const authSDK={getAuth:()=>auth,browserLocalPersistence:'local',setPersistence:async()=>{},onAuthStateChanged:(_auth,fn)=>{callback=fn;fn(auth.currentUser);},signInWithEmailAndPassword:async(_auth,email,password)=>{assert.equal(password,'secret-test');auth.currentUser={uid:'user-1',isAnonymous:false,email,displayName:'Player',getIdToken:async()=>'verified-token'};callback(auth.currentUser);return {user:auth.currentUser};},createUserWithEmailAndPassword:async(...args)=>authSDK.signInWithEmailAndPassword(...args),updateProfile:async(user,fields)=>Object.assign(user,fields),signOut:async()=>{auth.currentUser=null;callback(null);},signInAnonymously:async()=>{auth.currentUser={uid:'guest-1',isAnonymous:true,getIdToken:async()=>'guest-token'};callback(auth.currentUser);},sendPasswordResetEmail:async(_auth,email)=>writes.push(['reset',email])};
 const dbSDK={getDatabase:()=>({}),ref:(_db,path)=>path,get:async path=>({val:()=>data[path]||null}),set:async(path,value)=>{writes.push([path,value]);data[path]=value;},serverTimestamp:()=>123456};
 const window={MadaarFirebaseConfig:{firebase:{apiKey:key}},dispatchEvent:()=>{}};
 const context={window,sessionStorage,localStorage,Event:class{},loadSDK:async url=>url.endsWith('firebase-app.js')?{initializeApp:()=>({})}:url.endsWith('firebase-auth.js')?authSDK:dbSDK};vm.runInNewContext(source,context);return {api:window.MadaarFirebase,auth,writes,sessionStorage,localStorage,data};}
(async()=>{const missing=environment('');await assert.rejects(missing.api.login('x@test.com','secret-test'),/apiKey/);assert.equal(missing.sessionStorage.map.size,0);
const env=environment('public-test-key');await env.api.login('player@test.com','secret-test');assert.equal(JSON.parse(env.sessionStorage.getItem('madaarSession')).uid,'user-1');assert.equal(await env.api.token(),'verified-token');assert(![...env.sessionStorage.map.values(),...env.localStorage.map.values()].some(value=>value.includes('secret-test')));
await env.api.saveProfile({displayName:'Player',language:'en',category:1,newLearner:true,score:999,password:'never-write'});const [path,profile]=env.writes[0];assert.equal(path,'users/user-1/profile');assert.equal(profile.score,undefined);assert.equal(profile.password,undefined);assert.equal(profile.language,'en');assert.equal(profile.category,1);
env.data['users/user-1']={profile,results:{session:{score:3}}};const restored=await env.api.readAccount();assert.equal(restored.results.session.score,3);assert.equal(env.api.getProfile().displayName,'Player');await env.api.resetPassword('player@test.com');assert.deepEqual(env.writes.at(-1),['reset','player@test.com']);await env.api.logout();assert.equal(env.auth.currentUser,null);assert.equal(env.sessionStorage.getItem('madaarSession'),null);await env.api.guest();assert.equal(env.auth.currentUser.isAnonymous,true);const count=env.writes.length;await env.api.saveProfile({displayName:'Guest'});assert.equal(env.writes.length,count);
const rules=JSON.parse(fs.readFileSync('madaar_web/integration/firebase/database.rules.json','utf8')).rules;assert.equal(rules['.read'],false);assert.equal(rules['.write'],false);assert.equal(rules.users.$uid.results['.write'],false);assert.equal(rules.users.$uid.progress['.write'],false);assert.equal(rules.onlinePrivate['.read'],false);assert.equal(rules.onlinePrivate['.write'],false);
console.log('Firebase adapter passed with a test SDK: missing-key errors, auth/session/guest/logout, profile filtering, cross-device data retrieval contract and server-only result paths. Real Firebase remains untested.');})().catch(error=>{console.error(error);process.exit(1);});
